### ISSUE TITLE
A Schematic of the wiring to the powersupply and G-Shield would help those unfamiliar with wiring

### ISSUE THREAD

**Issue by Casadelwhacos** [inventables/x-carve-instructions#21]
I found this while searching the forums and thought it might help those unfamiliar with wiring. The pictures do a good job but a schematic would solve some issues especially when connecting the limit switch wires. Currently the only wiring schematic is just for the steppers

![wiring](https://cloud.githubusercontent.com/assets/12847784/8111235/ae45fa00-102e-11e5-8ff1-290c9cd47784.jpg)

**Comment by paulkaplan** [comment]
@chrisbalin what is the status of this?

**Comment by vaporlock** [comment]
+1 for this. This one image replaces the whole page. The instructions don't even list the pin numbers. We are forced to count black holes in a black connector. The orientation of the connector is also not specifically called out as a caution. Anytime something can be hooked up backwards it will be. The limit switch ground wires don't fit well in the board ground connector and should either be spliced in before the screw down or connected to the PS ground, which is on the same wire. Is noise a potential reason not to do this? If so, better to tie them to the actual ground pin on the board rather than power ground.

**Comment by chrisbalin** [comment]
@johndudleyhayes Were you going to make your own version of this diagram?
